# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
profile: true
title:            'IMSHAKIL'
tagline:          'Support Engineer | Gluu.org'
description:      ''
url:              https://github.com/imshakil
baseurl:          ''

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
