# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            imShakil
tagline:          'A Personal Blog'
description:      'Support Engineer | Gluu'
url:              https://fongandrew.github.io
baseurl:          ''

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

google_ad_client: ca-pub-2449944472030683
google_analytics: G-8KPHQTM1B5
